#loc_types.hidden = "dowsingmachine_if_opt"
#
#enc_types.surf = "surf"
#enc_types.good_rod = "good_rod"
#enc_types.old_rod = "old_rod"
#enc_types.super_rod = "super_rod"
#enc_types.rock_smash = "rock_smash"
#enc_types.day = "daytime"
#enc_types.morning = "morningtime"
#enc_types.night = "nighttime"
#enc_types.fishing_night = "(old_rod | good_rod | super_rod) & nighttime"
#
#common.evo_item_shop = "event_goldenrod_store if !evo_items_shop_in_ap_helper"
#
#common.cut = "hm01 & cut_badge & use_cut"
#common.fly = "hm02 & fly_badge & use_fly"
#common.surf = "hm03 & surf_badge & use_surf"
#common.strength = "hm04 & strength_badge & use_strength"
#common.whirlpool = "hm05 & whirlpool_badge & use_whirlpool"
#common.rock_smash = "hm06 & rock_smash_badge & use_rock_smash"
#common.waterfall = "hm07 & waterfall_badge & use_waterfall"
#common.rock_climb = "hm08 & rock_climb_badge & use_rock_climb"
#common.flash = "tm70 & use_flash"
#
#common.national_dex = "pokedex * 2"
#common.dowsingmachine_if_opt = "dowsing_mchn if dowsing_machine_logic"
#common.flash_if_opt = "flash if visibility_hm_logic"
#
#exits.virt_start.virt_dex = "pokedex if dexsanity_mode >= option_req"
#exits.virt_start.virt_national_dex = "national_dex if dexsanity_mode >= option_req"
